# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "wrapi"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["dannguyen"]
  s.date = "2013-10-10"
  s.description = "A thin layer for API calls"
  s.email = "dansonguyen@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/facebook_wrangler.rb",
    "examples/instagram_wrangler.rb",
    "examples/twitter_wrangler.rb",
    "examples/youtube_wrangler.rb",
    "lib/wrapi.rb",
    "lib/wrapi/client_queue.rb",
    "lib/wrapi/error.rb",
    "lib/wrapi/error_collector.rb",
    "lib/wrapi/fetch_process.rb",
    "lib/wrapi/fetched_response.rb",
    "lib/wrapi/fetcher.rb",
    "lib/wrapi/managed_client.rb",
    "lib/wrapi/wrangler.rb",
    "spec/fixtures/tweets/383324104641613823.json",
    "spec/fixtures/tweets/383380477509636095.json",
    "spec/fixtures/tweets/383637214972100607.json",
    "spec/fixtures/tweets/383667388308529151.json",
    "spec/fixtures/tweets/383742861709434879.json",
    "spec/fixtures/tweets/383969384785805311.json",
    "spec/integrated/twitter_wrangler_spec.rb",
    "spec/integrated/wrangler_client_spec.rb",
    "spec/integrated/wrangler_timed_client_spec.rb",
    "spec/integration_helper.rb",
    "spec/lib/client_queue_spec.rb",
    "spec/lib/fetch_process_error_handling_spec.rb",
    "spec/lib/fetch_process_spec.rb",
    "spec/lib/fetched_response_spec.rb",
    "spec/lib/fetcher_calls_spec.rb",
    "spec/lib/fetcher_spec.rb",
    "spec/lib/managed_client_spec.rb",
    "spec/lib/wrangler_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dannguyen/wrapi"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.5"
  s.summary = "A wrapper for API calling libraries"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_runtime_dependency(%q<andand>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2.14"])
      s.add_runtime_dependency(%q<awesome_print>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
    else
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<andand>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["~> 3.2.14"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<timecop>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<andand>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["~> 3.2.14"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.14.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<timecop>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
  end
end

